set tabstop=4 "number ov visual spaces per TAB

set softtabstop=4 " number of spaces in tab when editing

set expandtab " tabs become spaces

set number " shows line numbers

set showcmd "shows command at bottom

set cursorline "highlight current line

set showmatch "highlight matching for []{}()

colo desert
